name: almabad
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.6+7

environment:
  sdk: ^3.5.3

dependencies:
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.5.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.6
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.1
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.2
  google_sign_in: ^6.2.2
  internet_connection_checker: ^1.0.0+1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  translator: ^1.0.3+1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#F8ECC8"
  image: "assets/icon/logo_android12.png"
  android_12:
    color: "#F8ECC8"
    image: "assets/icon/logo_android12.png"
  android: true
  ios: true

flutter_launcher_icons:
  adaptive_icon_foreground: "assets/images/toot.png"
  adaptive_icon_background: "#ffffff"
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/toot.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/music/
    - assets/icon/
  fonts:
    - family: EnglishPheroni
      fonts:
        - asset: assets/fonts/EnglishPheroni.ttf
    - family: Egyptian
      fonts:
        - asset: assets/fonts/Egyptian.ttf
    - family: Arabic
      fonts:
        - asset: assets/fonts/Arabic.ttf
flutter_intl:
  enabled: true
